FORMAT: 1A
HOST: /api/v1/genres-api

# Genres Micro-Service
This is the API description of a Genres microservice
<!-- include(events/index.apib) -->
<!-- include(breadcrumbs/index.apib) -->
<!-- include(lagging/index.apib) -->
<!-- include(leading/index.apib) -->
<!-- include(trips/index.apib) -->
<!-- include(reports/index.apib) -->
<!-- include(kpi/index.apib) -->
